name: Check

on:
  push:
    branches:
      - "develop"
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: ESLint
        run: npx eslint ./src .

      - name: Prettier
        run: npx prettier --write ./src .

      - name: Build
        run: npm run build
